version: '3.8'
services:

  nginx-mytheresa:
    image: nginx:stable-alpine
    container_name: mytheresa-webserver
    volumes:
      - ../mytheresa_app/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8050:80"
    depends_on:
      - php-mytheresa
    networks:
      - mytheresa_network

  php-mytheresa:
    build:
      context: php
    container_name: mytheresa-php
    environment:
      DB_HOST: db-mytheresa
      DB_PORT: 5432
    volumes:
      - ../mytheresa_app:/var/www/app
    expose:
      - "9000"
    depends_on:
      - db-mytheresa
    networks:
      - mytheresa_network

  db-mytheresa:
    image: postgres:16-alpine
    container_name: mytheresa-db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "8051:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mytheresa_network

volumes:
  db_data:

networks:
  mytheresa_network:
    driver: bridge
